var pg = require("pg");

//Wrapper for all database functionality
var DB = function() {
    //Environment specific constructor
    if (process.env.development == "true") {
        //Database in C9 environment - remember to set development = true in environment
        this.connString = "postgres://postgres:postgres@localhost/biscuit";
    }
    else {
        //TBC username + password + ip
        this.connString = "postgres://postgres:postgres@randomhost/biscuit";
    }

};


//Checks if tables exist, if not, creates them
DB.prototype.setupDB = function() {
    var client = new pg.Client(this.connString);
    client.connect(function(err) {
        if (err) {
            return console.error('Could not connect to postgres', err);
        }
        //Create tblUsers
        client.query("CREATE TABLE IF NOT EXISTS tblUsers  ( \
                    id SERIAL, \
                    gender VARCHAR(10), \
                    firstName VARCHAR(50), \
                    lastName VARCHAR(50), \
                    DOB DATE, \
                    number VARCHAR(20), \
                    email VARCHAR(100), \
                    pictureURL VARCHAR(200), \
                    serviceID VARCHAR(50) NOT NULL, \
                    serviceName VARCHAR(20) \
                    );", function(err, result) {
            if (err) {
                return console.error('Error:', err);
            }
            console.info('tblUsers processed');
        });
        //Create tblQueue
        client.query("CREATE TABLE IF NOT EXISTS tblQueue ( \
                    id SERIAL, \
                    userID INT, \
                    genderpreference VARCHAR(10), \
                    publicX FLOAT, \
                    publicY FLOAT, \
                    gpsX FLOAT, \
                    gpsY FLOAT, \
                    publicName VARCHAR(50), \
                    endDate DATE, \
                    activityName VARCHAR(50) \
                    );",
            function(err, result) {
                if (err) {
                    return console.error('Error:', err);
                }
                console.info('tblQueue processed');
            });

        //Create tblMatches
        client.query("CREATE TABLE IF NOT EXISTS tblMatches ( \
                    id SERIAL, \
                    userID INT, \
                    genderpreference VARCHAR(10), \
                    publicX FLOAT, \
                    publicY FLOAT, \
                    gpsX FLOAT, \
                    gpsY FLOAT, \
                    publicName VARCHAR(50), \
                    endDate DATE, \
                    activityName VARCHAR(50) \
                    );",
            function(err, result) {
                if (err) {
                    return console.error('Error:', err);
                }
                console.info('tblMatches processed');
            });
        console.info('DB initialised successfully');
    });
};

/*
@parameter user (firstName, lastName, gender, dob, number, email, pictureURL, serviceID, serviceName)
@parameter onComplete callback function(userID)
*/
DB.prototype.addUser = function(user, onComplete) {
    pg.connect(this.connString, function(err, client, done) {
        if (err) {
            return console.error('Error fetching client from pool', err);
        }

        //Temporarily stores user id that was generated by db on insert 
        var userID;
        //Insert the user entry
        var queryUsers = client.query({
            text: 'SELECT id \
                FROM tblUsers \
                WHERE serviceID = $1 \
                AND serviceName = $2;',
            values: [user.serviceID, user.serviceName],
            name: 'get id'
        });

        queryUsers.on('error', function(err) {
            console.log('Error:', err);
        });
        //Temporary fix for getting result as error is returned on end ?!
        queryUsers.on('row', function(row, result) {
            if (row.id) {
                userID = row.id;
            }
        });

        //On the end of the query call callback with userid
        queryUsers.on('end', function(err, result) {
            done();
            if (!userID) {
                console.log("Inserting new user");
                //Insert the user entry
                var queryInsertUsers = client.query({
                    text: 'INSERT INTO tblUsers \
                (firstname, lastname, email, gender, dob, number, pictureurl, servicename, serviceid) \
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) \
                RETURNING id;',
                    values: [user.firstName, user.lastName, user.email, user.gender, user.DOB, user.number, user.pictureURL, user.serviceName, user.serviceID],
                    name: 'Insert user details'
                });

                queryInsertUsers.on('error', function(err) {
                    console.log('Error:', err);
                });
                //Temporary fix for getting result as error is returned on end ?!
                queryInsertUsers.on('row', function(row, result) {
                    if (row.id) {
                        userID = row.id;
                    }
                });
                queryInsertUsers.on('end', function(err, result) {
                    done();
                    onComplete(userID);
                });
            }
            else onComplete(userID);
        });
    });
};

/*
@parameter userID 
@parameter matchDetails (userid, genderpreference, gpsx, gpsy, publicx, publicy, publicname, enddate, activityName)
@parameter onComplete callback function(requestID)
*/
DB.prototype.addRequest = function(userID, matchDetails, onComplete) {
    pg.connect(this.connString, function(err, client, done) {
        if (err) {
            return console.error('Error fetching client from pool', err);
        }
        done();
        //Insert match query
        var requestID;
        var queryMatch = client.query({
            text: 'INSERT INTO tblQueue \
                    (userid, genderpreference, gpsx, gpsy, publicx, publicy, publicname, enddate, activityName) \
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8) \
                    RETURNING id;',
            values: [userID, matchDetails.genderPreference, matchDetails.gpsX, matchDetails.gpsX, matchDetails.publicX, matchDetails.publicX, matchDetails.publicName, matchDetails.endDate],
            name: 'Insert queue request'
        });
        queryMatch.on('row', function(row, result) {
            if (row.id) {
                requestID = row.id;
            }
        });
        queryMatch.on('end', function(err, result) {
            done();
            console.log('Inserted a user', userID, 'into the queue');
            //Callback and finish
            onComplete(requestID);
        });
    });
};

module.exports = DB;